
<div class="main_wrapper">
		<h1>Item uploading</h1>
		<div id="item_process" class="item_process">
			
		</div>
</div>


<button type="button" name="some_name" class="some class" onclick="checkSelectedItem()">Import Products</button>
<br><span id="results"></span>
                         
<style>
	.item_process {
		width: 100%;
		height: auto;
	}
	
	.progress {
		width: 50%;
		height: 22px;
		margin-bottom: 10px;
		padding: 2px 10px;
		color:green;
		border:1px solid green;
	}
	
	.error {
		width: 50%;
		height: 22px;
		margin-bottom: 10px;
		padding: 2px 10px;
		border: 1px solid red;
	}
</style>
<script type="text/javascript">
		var childNumber = 0;
		function checkSelectedItem(value){
			var reloadurl =  '<?php echo $this->getUrl('*/*/importcountajax') ?>';
			
			new Ajax.Request(reloadurl, {
				method: 'get',
				parameters: {upload_pr: childNumber},
				//onComplete: function(selectElement) { // Some on complete behaviour },
				onSuccess: function(selectElement) {
				
					var results = JSON.parse(selectElement.responseText);
					
					console.log(results);
					if(typeof results.error != 'undefined') {
						var errorsprint = document.getElementById('item_process');
						var errorelement = "<div class=\"error 1\">"+childNumber+" product "+results.product_id + results.error+" uploaded.. </div>";
						errorsprint.insertAdjacentHTML("beforeend",errorelement);
						//return;
					}else{
						var parent = document.getElementById('item_process');
						var newChild = "<div class=\"progress 1\">"+childNumber+" product "+results.product_id+" uploaded.. </div>";
						parent.insertAdjacentHTML('beforeend', newChild);
					}
					childNumber++;
					
					if(results.message == "continue"){
						checkSelectedItem();
					}
				}
			});
		}                         
</script>